server:
  port: 8000

spring:
  application:
    name: yayatao-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: an
          uri: 'lb://yayatao-member-service'
          predicates:
            - Path=/member/*
      filters:
        # 熔断降级配置
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/defaultfallback'
      httpclient:
        connectTimeout: 3000
        responseTimeout: 3000
        pool:
          type: elastic
          maxIdleTime: 30s



      # hystrix 信号量隔离，3秒后自动超时
      hystrix:
        command:
          default:
            execution:
              isolation:
                strategy: SEMAPHORE
                thread:
                  timeoutInMilliseconds: 3000
        shareSecurityContext: true


eureka:
  instance:
    prefer-ip-address: true
    #ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka/,http://eureka02:8762/eureka/,http://eureka03:8763/eureka/

