server:
  port: 8000

spring:
  application:
    name: yayatao-cloud-gateway

eureka:
  instance:
    prefer-ip-address: true
    #ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.10.127:8761/eureka

