server:
  port: 8762

eureka:
  instance:
    hostname: eureka02
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka/,http://eureka03:8763/eureka/
  server:
    enableSelfPreservation: false