server:
  port: 8763

eureka:
  instance:
    hostname: eureka03
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka/,http://eureka02:8762/eureka/
  server:
    enableSelfPreservation: false