server:
  port: 8001

spring:
  application:
    name: yayatao-member-service

eureka:
  instance:
    preferIpAddress: true
    #ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka

